-- Disable RLS on forum tables for testing
ALTER TABLE forum_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_topics DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE forum_views DISABLE ROW LEVEL SECURITY; 