-- Insert lessons for module 4: Finance & Business
-- Run this SQL in your Supabase SQL editor

INSERT INTO academy_lessons (
    module_id,
    title,
    duration,
    type,
    status,
    order_index,
    views,
    completion_rate,
    video_url,
    content,
    created_at,
    updated_at
) VALUES 
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Financiële Basis Begrippen',
    '30m',
    'video',
    'published',
    1,
    0,
    0,
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    '',
    NOW(),
    NOW()
),
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Budgetteren en Geld Management',
    '25m',
    'text',
    'published',
    2,
    0,
    0,
    '',
    'Budgetteren is de fundering van financiële gezondheid. Leer hoe je je geld slim beheert en controle krijgt over je financiën.',
    NOW(),
    NOW()
),
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Investeren voor Beginners',
    '35m',
    'text',
    'published',
    3,
    0,
    0,
    '',
    'Investeren is de sleutel tot financiële vrijheid. Leer de basisprincipes en begin veilig met beleggen.',
    NOW(),
    NOW()
),
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Ondernemerschap en Business',
    '40m',
    'video',
    'published',
    4,
    0,
    0,
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    '',
    NOW(),
    NOW()
),
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Passief Inkomen Opbouwen',
    '30m',
    'text',
    'published',
    5,
    0,
    0,
    '',
    'Passief inkomen is de sleutel tot financiële vrijheid. Leer hoe je inkomstenstromen kunt creëren die automatisch geld genereren.',
    NOW(),
    NOW()
),
(
    (SELECT id FROM academy_modules WHERE title = 'Finance & Business' LIMIT 1),
    'Reflectie & Integratie',
    '15m',
    'exam',
    'published',
    6,
    0,
    0,
    '',
    '',
    NOW(),
    NOW()
);
